<Project>

  <PropertyGroup>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Akeoott/kyanite-cli.git</RepositoryUrl>

    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Runtime.Versioning" />
  </ItemGroup>

</Project>